void fw_A_coefficient(int N, double L, const double complex *beta, const double *F, int izmax, double complex *A, bool absorption_resistant);
void fw2d_A_coefficient_restricted(int P, int N, double L, const double complex *beta, const double *F, int iymax, int izmax, double complex *A, bool absorption_resistant);
void fw3d_A_coefficient_restricted(int S, int P, int N, double L, const double complex *beta, const double *F, int ixmax, int iymax, int izmax, double complex *A, bool absorption_resistant);
double bb_spot_radius(double complex h, bool asymptotic);
double bb_penetration_depth(double complex beta);
double complex bb_axicon_angle(double complex k, double complex h, bool in_degree);
double bb_aperture_radius(double complex beta, double complex h, double L);
double bb_aperture_radius_max(double complex h);
double bb_aperture_radius_min(double complex h);
int fw_N_max(double Q, double L, double complex k);
double fw_Q_from_spot_radius_traditional(double complex k, double spot_radius, bool asymptotic);
double fw_Q_from_spot_radius_purely_real_h(double complex k, double spot_radius, bool asymptotic);
double fw_Q_from_spot_radius_paraxial_h(double complex k, double spot_radius, bool asymptotic);
double fw_absorption_resistant_condition(int N, const double complex *beta);
void fw_wavenumbers_traditional(int N, double Q, double L, double k0, double complex nref, double complex *k, double complex *beta, double complex *h);
void fw_wavenumbers_purely_real_h(int N, double Q, double L, double k0, double complex nref, double complex *k, double complex *beta, double complex *h);
void fw_wavenumbers_paraxial_h(int N, double Q, double L, double k0, double complex nref, double complex *k, double complex *beta, double complex *h);